### ISSUE TITLE
[BOOM-5821] BO Error on deleteting order lines in multi store mode.

### ISSUE THREAD

**Issue by PierreRambaud** [PierreRambaud/PrestaShop#192]
<b><i>[reporter="MARK-APP", created="Mon, 25 Jun 2018 10:22:57 +0200"]</i></b>
<p>If you enabled multi store in PrestaShop and you put your store selection on All shop, you won't be able to Delete product form your order.</p>

<p>After that you try to delete an order line it looks like nothing happened. If you check your PHP error log you will see it's genarates this php error:</p>

<p>PHP Fatal error:  Uncaught PrestaShopBundle\Exception\NotImplementedException: Shop context types other than "single shop" are not supported in /**********/src/PrestaShopBundle/Entity/Repository/StockManagementRepository.php:133<br/>
 Stack trace:<br/>
 #0 /**********/src/PrestaShopBundle/Entity/Repository/StockMovementRepository.php(57): PrestaShopBundle\Entity\Repository\StockManagementRepository->_<em>construct(Object(appProdProjectContainer), Object(Doctrine\DBAL\Connection), Object(Doctrine\ORM\EntityManager), Object(PrestaShop\PrestaShop\Adapter\LegacyContext), Object(PrestaShop\PrestaShop\Adapter\ImageManager), 'ps_bloemen</em>')<br/>
 #1 /*********<b>/app/cache/prod/appProdProjectContainer.php(2912): PrestaShopBundle\Entity\Repository\StockMovementRepository->__construct(Object(appProdProjectContainer), Object(Doctrine\DBAL\Connection), Object(Doctrine\ORM\EntityManager), Object(PrestaShop\PrestaShop\Adapter\LegacyContext), Object(PrestaShop\PrestaShop\A in /</b>*********/app/bootstrap.php.cache on line 3231</p>

**Comment by PierreRambaud** [comment]
<b><i>[author="khouloud.belguith", created="Mon, 25 Jun 2018 12:23:26 +0200"]</i></b>
<p>Hi Peter,</p>

<p>Thanks for the report.<br/>
I manage to reproduce the issue with the last version 1.7.4.0.-beta-1.<br/>
We will see how to fix it.</p>

<p>Best regards, Khouloud</p>

**Comment by PierreRambaud** [comment]
<b><i>[author="khouloud.belguith", created="Thu, 9 Aug 2018 12:14:59 +0200"]</i></b>
<p>Hi Peter Visser,</p>

<p>All shop is selected.<br/>
We xhange the order to payment accepted.<br/>
Invoice => OK<br/>
 <span class="image-wrap" style=""><a id="70306_thumb" href="http://forge.prestashop.com/secure/attachment/70306/70306_screenshot-2.png" title="screenshot-2.png" file-preview-type="image" file-preview-id="70306" file-preview-title="screenshot-2.png"><img src="http://forge.prestashop.com/secure/thumbnail/70306/_thumb_70306.png" style="border: 0px solid black" /></a></span> <br/>
After clicking delete product => Impossible => an exception is displayed<br/>
 <span class="image-wrap" style=""><a id="70305_thumb" href="http://forge.prestashop.com/secure/attachment/70305/70305_screenshot-1.png" title="screenshot-1.png" file-preview-type="image" file-preview-id="70305" file-preview-title="screenshot-1.png"><img src="http://forge.prestashop.com/secure/thumbnail/70305/_thumb_70305.png" style="border: 0px solid black" /></a></span> <br/>
We try to download again the invoice => OK => The product is deleted from the invoice but it is still displayed in the order details.<br/>
 <span class="image-wrap" style=""><a id="70307_thumb" href="http://forge.prestashop.com/secure/attachment/70307/70307_screenshot-3.png" title="screenshot-3.png" file-preview-type="image" file-preview-id="70307" file-preview-title="screenshot-3.png"><img src="http://forge.prestashop.com/secure/thumbnail/70307/_thumb_70307.png" style="border: 0px solid black" /></a></span> </p>

<p>Best regards, Khouloud</p>
